version: 2.1

orbs: 
  aws-ecr: circleci/aws-ecr@7.3.0

jobs: 
  build-and-publish:
    docker:
      - image: cimg/python:3.10.7-node
    resource_class: small
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Build Dependencies
          command: |
            pip install -r requirements.txt
            npm install
      - run:
          name: Build Components
          command: |
            npm run build
      - run:
          name: Set Environment Variables
          command: |
            echo "export BUILD_DATE=$(date +%Y-%m-%d-%H-%M-%S)" >> $BASH_ENV
            echo 'export SHORT_SHA=$(echo ${CIRCLE_SHA1} | cut -c1-8)' >> $BASH_ENV
            echo 'export FULL_VERSION="0.0.0+$BUILD_DATE-$SHORT_SHA"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Authenticate to CodeArtifact
          command: |
            pip install awscli
            echo "export POETRY_HTTP_BASIC_WHETSTONEPYTHON_USERNAME=aws" >> $BASH_ENV
            echo "export POETRY_HTTP_BASIC_WHETSTONEPYTHON_PASSWORD=$(aws codeartifact get-authorization-token --domain-owner 676770652859 --domain wsaipipes-repos-codeartifact-domain --query 'authorizationToken' --output text)" >> $BASH_ENV
      - run:
          name: Build Python Package
          command: |
            poetry version "$FULL_VERSION"
            poetry build
      - run:
          name: Publish Python Package
          command: |
            echo "Poetry publish username: $POETRY_HTTP_BASIC_WHETSTONEPYTHON_USERNAME"
            poetry publish -r whetstonepython

workflows:
  build-and-publish:
    jobs:
      - build-and-publish:
          context:
            - whetstone-aws-auth
