version: 2.1

orbs: 
  aws-ecr: circleci/aws-ecr@7.3.0

jobs: 
  build-and-publish:
    docker:
      - image: cimg/python:3.10.7-node
    resource_class: small
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Check/Run Poetry Update
          command: |
            pip install -r requirements.txt
            npm install
      - run:
          name: Build Components
          command: |
            npm run build

workflows:
  build-and-publish:
    jobs:
      - build-and-publish
