version: 2.1

orbs:
  node: circleci/node@18.10

jobs: 
  build-project:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - node/run:
          npm-run: build

workflows:
  build-and-publish:
    jobs:
      - build-project
