version: 2.1

orbs: 
  aws-ecr: circleci/aws-ecr@7.3.0

jobs: 
  build-project:
    docker:
      - image: cimg/python:3.10.7-node
    resource_class: small
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Check/Run Poetry Update
          command: npm run build

workflows:
  build-and-publish:
    jobs:
      - build-project:
          context:
            - whetstone-aws-auth
