version: 2.1

orbs:
  node: circleci/node@18.9.1

jobs: 
  build-project:
    docker:
      - image: cimg/python:3.9
    resource_class: small
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Check/Run Poetry Update
          command: npm run build

workflows:
  build-and-publish:
    jobs:
      - build-project:
          context:
            - whetstone-aws-auth
